import argparse
import os

import numpy as np
from sklearn.decomposition import PCA


def parse_args():
    parser = argparse.ArgumentParser(
        description='Evaluate how well PCA compresses and preserves variance for saved BERT embedding vectors.'
    )
    parser.add_argument(
        '--input',
        required=True,
        help='Path to a PCA .npz file generated by train.py --pca_only.',
    )
    parser.add_argument(
        '--max-components',
        type=int,
        default=50,
        help='Maximum number of PCA components to evaluate.',
    )
    parser.add_argument(
        '--variance-thresholds',
        type=float,
        nargs='+',
        default=[0.8, 0.9, 0.95, 0.99],
        help='Cumulative explained variance thresholds to inspect.',
    )
    return parser.parse_args()


def format_ratio(value):
    return '{:.2f}%'.format(value * 100.0)


def find_min_components(cumulative_variance, threshold):
    reached = np.where(cumulative_variance >= threshold)[0]
    if reached.size == 0:
        return None
    return int(reached[0] + 1)


def main():
    args = parse_args()
    data = np.load(args.input)
    vectors = data['vectors']

    n_samples, n_features = vectors.shape
    max_components = min(args.max_components, n_samples, n_features)
    if max_components < 1:
        raise ValueError('No valid component count can be evaluated.')

    pca = PCA(n_components=max_components)
    reduced = pca.fit_transform(vectors)
    reconstructed = pca.inverse_transform(reduced)

    explained_variance_ratio = pca.explained_variance_ratio_
    cumulative_variance = np.cumsum(explained_variance_ratio)
    mse_per_component = ((vectors - reconstructed) ** 2).mean()

    print('Input file      : {}'.format(os.path.abspath(args.input)))
    print('Samples         : {}'.format(n_samples))
    print('Original dim    : {}'.format(n_features))
    print('Evaluated up to : {} components'.format(max_components))
    print()
    print('Top principal components')
    for idx, ratio in enumerate(explained_variance_ratio[: min(10, len(explained_variance_ratio))], start=1):
        print('PC{:>2}: variance={} cumulative={}'.format(idx, format_ratio(ratio), format_ratio(cumulative_variance[idx - 1])))

    print()
    print('Minimum components to reach target variance')
    for threshold in args.variance_thresholds:
        min_components = find_min_components(cumulative_variance, threshold)
        if min_components is None:
            print('threshold={} -> not reached within {} components'.format(format_ratio(threshold), max_components))
            continue
        compression_ratio = min_components / n_features
        print(
            'threshold={} -> {} components, compression_ratio={}, reduced_dim={}/{}'.format(
                format_ratio(threshold),
                min_components,
                format_ratio(compression_ratio),
                min_components,
                n_features,
            )
        )

    print()
    print('Reconstruction quality')
    print('MSE with {} components: {:.8f}'.format(max_components, mse_per_component))

    print()
    print('Assessment guide')
    print('- PCA is helpful if a small number of components reaches a high cumulative variance.')
    print('- Compression is strong when reduced_dim/original_dim is low.')
    print('- Lower reconstruction MSE means less information loss after projection.')
    print('- If 90%-95% variance needs too many components, PCA is not compressing BERT embeddings effectively.')


if __name__ == '__main__':
    main()
