#!/bin/bash

# * laptop

# * Teacher: SSEGCN-BERT
python ./train.py --model_name ssegcnbert --dataset laptop --seed 1000 --bert_lr 2e-5 --num_epoch 10 --hidden_dim 768 --max_length 100 --vocab_dir ./dataset/Laptops_corenlp --cuda 0

# * Student: distill from SSEGCN-BERT
# Replace --teacher_path with the checkpoint generated by the teacher run above.
# python ./train.py --model_name ssegcnbertstudent --dataset laptop --seed 1000 --num_epoch 20 --max_length 100 --vocab_dir ./dataset/Laptops_corenlp --teacher_path ./state_dict/ssegcnbert_laptop_acc_0.8000_f1_0.7500 --student_hidden_dim 32 --student_pos_dim 8 --student_post_dim 8 --student_lr 1e-3 --kd_temperature 4.0 --kd_alpha 0.4 --kd_beta 0.4 --kd_gamma 0.2 --cuda 0


# * restaurant

# * Teacher: SSEGCN-BERT
# python ./train.py --model_name ssegcnbert --dataset restaurant --seed 1000 --bert_lr 2e-5 --num_epoch 15 --hidden_dim 768 --max_length 100 --vocab_dir ./dataset/Restaurants_corenlp --cuda 0

# * Student: distill from SSEGCN-BERT
# python ./train.py --model_name ssegcnbertstudent --dataset restaurant --seed 1000 --num_epoch 20 --max_length 100 --vocab_dir ./dataset/Restaurants_corenlp --teacher_path ./state_dict/ssegcnbert_restaurant_acc_0.8000_f1_0.7500 --student_hidden_dim 32 --student_pos_dim 8 --student_post_dim 8 --student_lr 1e-3 --kd_temperature 4.0 --kd_alpha 0.4 --kd_beta 0.4 --kd_gamma 0.2 --cuda 0


# * twitter

# * Teacher: SSEGCN-BERT
# python ./train.py --model_name ssegcnbert --dataset twitter --seed 1000 --bert_lr 2e-5 --num_epoch 15 --hidden_dim 768 --max_length 100 --vocab_dir ./dataset/Tweets_corenlp --cuda 0

# * Student: distill from SSEGCN-BERT
# python ./train.py --model_name ssegcnbertstudent --dataset twitter --seed 1000 --num_epoch 20 --max_length 100 --vocab_dir ./dataset/Tweets_corenlp --teacher_path ./state_dict/ssegcnbert_twitter_acc_0.8000_f1_0.7500 --student_hidden_dim 32 --student_pos_dim 8 --student_post_dim 8 --student_lr 1e-3 --kd_temperature 4.0 --kd_alpha 0.4 --kd_beta 0.4 --kd_gamma 0.2 --cuda 0
